### ISSUE TITLE
Meta: Refactoringtermine

### ISSUE THREAD

**Issue by SaturnHafen** [hpi-swa-teaching/ProjectBoard#99]
- [ ] Samstag bis 15:00 Uhr: Kiet & Matthias
- [ ] Samstag ab 15:00 Uhr: Lina
- [ ] Sonntag irgendwann: Jannik
- [ ] Montag ab 10:00 Uhr: Luke & Kien
